# Numpy Nedir?

elimizde çok büyük sayıda veri var ise bu verileri numpy objeleri içerisine alıp bu şekilde kullanmak için böyle bir şey var

artıları
+ daha az yer kaplıyor
+ çok daha hızlı çalışıyorlar

        np.array()

In [2]:
py_list = [1,2,3,4,5,6,7,8,9]
# bu normal bir python listesi numpy de ise listeye array diyeceğiz

import numpy as np  # numpy kütüphanesine takma isim verdik

# numpy array
np_array_objemiz = np.array([1,2,3,4]) # köşeli parantez kullanmamızın nedeni parametre olarak sadece bir liste gönderdik anlamı vermek için

# bu iki objenin tipini öğrenelim
print(type(py_list))
print(type(np_array_objemiz))


<class 'list'>
<class 'numpy.ndarray'>


yukarıda oluşturduğumuz ve tipini sorguladığımız np_array_objemiz bir tek boyutlu dizi idi.

#### peki çok boyutlu bir dizi oluşturmak istersek..

        np.reshape()

In [21]:
# python listesi ile yapacak olsaydık
py_multi = [[1,2,3],[4,5,6],[7,8,9]]

# numpy array ile...
np_array = np.array([1,2,3,4,5,6,7,8,9])
np_multi = np_array.reshape(3,3) # mesela 9 elemanlı bir liste ise 3 e 3 lük bir matris oluşturuyoruz (3 satır ve 3 kolondan oluşan bir dizi yapısı)

# ekrana yazdıralım
print(py_multi)
print(np_multi)

# bu dizilerin çok boyutlu mu tek boyutlu mu olduğunu yazdıralım.
print(np_array.ndim)
print(np_multi.ndim)

# shape lerine bakalım
print(np_array.shape)   # (9,) tek boyutlu olduğunu ima eder
print(np_multi.shape)   # 3 e 3 lük bir matris olduğunu söyler

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
(9,)
(3, 3)
