# Numpy dizileri ile çalışmak

In [50]:
import numpy as np

# dizi oluşturalım
result = np.array([1,3,5,7,9])
print(result)

# peki elemanları kendimiz belirtmek istemediğimiz zaman...
result = np.arange(1,10)    # range metodunu hatırla onun gibi
print(result)

# 10 ile 100 arası vir veri olsun ve artış miktarı 3 olsun
result = np.arange(10,100,3)
print(result)

# sıfırlardan oluşsun istersek veri grubu
result = np.zeros(10)
print(result)   # 10 tane sıfırı yan yana koyar
            #not her bir elemanı float bir değere karşılık geliyor dikkat et

# birlerden oluşan bir veri olsun istersek
result = np.ones(10)
print(result)
            #not her bir elemanı float bir değere karşılık geliyor dikkat et

# belli bir aralıkta ve eşit bir artışa sahip dizi oluşturalım
result = np.linspace(0,100,5)   # 5 eşit parçaya bölsün
print(result)

# başka bir örnek daha
result = np.linspace(0,5,5)
print(result)

# sıfırla 9 arası bir sayı üretir. her çalıştırmada farklı
result = np.random.randint(0,10)
print(result)

# sadece üst değeri verirsen sıfırdan o değere kadar alır
result = np.random.randint(20)
print(result)

# bir ile 10 arası sayılardan rastgele 3 ünü versin bize
result = np.random.randint(1,10,3)
print(result)

# sıfırla bir arasında beş sayı üretsin
result = np.random.rand(5)
print(result)

# yukarıdakinin - değerler de katılmış hali
result = np.random.randn(5)
print(result)

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[0.   1.25 2.5  3.75 5.  ]
7
6
[6 2 1]
[0.55417062 0.57893815 0.96764302 0.65139098 0.1297609 ]
[ 0.70000535 -1.11959948 -1.69318927  1.24324397  0.6602226 ]


In [53]:
import numpy as np

# 5 e 10 luk bir matris oluşturuyoruz
np_array = np.arange(50)
result = np_array.reshape(5,10)

print(result)

# satırların toplamını hesaplatalım
print(result.sum(axis=1))

# axis= 0 yaparsak sütunların toplamını verir
print(result.sum(axis=0))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]


In [66]:
# bir ile 100 arası 10 tane sayı üretelim
random_numbers = np.random.randint(1,100,10)
print(random_numbers)

# yukarıdaki üretilen sayılardan en büyüğü hangisi...
result_max = random_numbers.max()
print(result_max)

# en küçüğü hangisi...
result_min = random_numbers.min()
print(result_min)

# üretilen sayılardan en büyük olanın index numarasını bana ver
result = random_numbers.argmax()
print(result)

# bu sefer en küçüğünün index numarasını ver
result = random_numbers.argmin()
print(result)

[12 70 54 82 51 57 19 11 64 85]
85
11
9
7
