# Numpy Dizilerinin Indexlenmesi

In [10]:
import numpy as np

# numpy dizisi oluşturup elemanlarını kendimiz tanımlayalım
numbers = np.array([0,5,10,15,20,25,50,75])

# burdaki oluşturduğumuz tek boyutlu liste elemanlarına ulaşmaya çalışalım
result = numbers[5]     # 5. indexe ulaşırız
print(result)

# en sağdan başlayıp 5. indexe ulaşalım bu seferde
result = numbers[-5]
print(result)

# sıfır ile 3 arası değerleri yazdırmak istersek
result = numbers[0:3]
print(result)

# 3. indexten başla ve sona kadar git demiş olsak
result = numbers[3:]
print(result)

# tüm listeyi istersek
result = numbers[::]
print(result)

# tüm listeyi ters çevirmek istersek
result = numbers[::-1]      # 3. parametre adım sayısıdır adım sayısını -1 yaparsak birer birer tersten gel demek olur
print(result)

25
15
[ 0  5 10]
[15 20 25 50 75]
[ 0  5 10 15 20 25 50 75]
[75 50 25 20 15 10  5  0]


#### iki boyutlu bir dizi oluşturalım

In [39]:
import numpy as np
numbers = np.array([[0,5,10],[15,20,25],[50,75,85]])
print(numbers)

# numbers ın sıfırıncı indexindeki elemana ulaşmaya çalışalım
result = numbers[0]
print(result)   # ilk grup 0. indexmiş yani

# ikinci indexteki elemana ulaşalım
result = numbers[2]
print(result)

# bu her bir indexteki elemanlar bir nevi satır da oluyor aynı zamanda


# birinci indexteki grubun içindeki  elemanları alalım bu sefer.
result = numbers[0,2]
print(result)   # 0. indexteki grubun içinden 2. indexin elemanını aldı

# bu sefer 2. indexteki grubun 1. indexini alalım
result = numbers[2,1]
print(result)

# [:] dersek tüm satırları seçmiş oluruz
# [:,2] dersek eğer seçtiğimiz tüm satırlardan ikinci kolonu alsın demiş oluruz
result = numbers[:,2]
print(result)

# bu sefer ilk kolonu getirelim
result = numbers[:,0]
print(result)

# yine tüm satırları seç ama 0 ile 2. index arası elemanları al
result = numbers[:,0:2]
print(result)

# başına -1, koyarak son satırı seçsin anlamı veriyoruz
result = numbers[-1,:]
print(result)

# 2 dahil deil o nedenle 0 ile 1. indexdeki kolon ve satırları aldık
result = numbers[:2,:2]
print(result)

[[ 0  5 10]
 [15 20 25]
 [50 75 85]]
[ 0  5 10]
[50 75 85]
10
75
[10 25 85]
[ 0 15 50]
[[ 0  5]
 [15 20]
 [50 75]]
[50 75 85]
[[ 0  5]
 [15 20]]


In [44]:
import numpy as np

arr1 = np.arange(0,10)
arr2 = arr1 # referans kopyalama yapmıs olduk

print(arr1)
print(arr2)

# arr2 üzerinden herhangi bir elemana ulaşmaya çalışalım

# arr2  üzerindeki 0. indexi 20 ile değiştirmeyi deneyelim
arr2[0] = 20
print(arr1)
print(arr2)
    # arr2 üzerinde yaptığımız değişiklik arr1 ide etkiledi çünkü aynı adresteki veriler üzerinde değişikliğe tabi tuttuk


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]
[20  1  2  3  4  5  6  7  8  9]


yukarıda yaptığımız referans kopyalaması yerine arr1 üzerinden 

        copy()

metodu aracılığı ile bir kopyalama işlemi yapabilirim.
bunu yaptığımda arr1 ve arr2 için farklı adresler olacak.

In [45]:
import numpy as np

arr1 = np.arange(0,10)
arr2 = arr1.copy()

print(arr1)
print(arr2)

# yine arr2 üzerinden herhangi bir elemana ulaşmaya çalışalım

# yine arr2  üzerindeki 0. indexi 20 ile değiştirmeyi deneyelim
arr2[0] = 20
print(arr1)
print(arr2) 
        # bu sefer adresler farklı olduğu için arr1 etkilenmedi sadece arr2 etkilendi

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]
