# Numpy Dizi Operasyonları

In [15]:
import numpy as np

# rastgele iki farklı dizi oluşturacak
numbers1 = np.random.randint(10,100,6)  # 10 ile 100 arası rastgele sayı üretsin
numbers2 = np.random.randint(10,100,6)

print(numbers1)
print(numbers2)

# rastgele oluşturduğumuz diziyi toplayabiliriz.

result = numbers1 + numbers2
print(result)   # iki dizinin aynı indexteki elemanlarını topluyor ve dizi olarak grupluyor.

# veya şöyle de yapabiliriz
result = numbers1 + 10
print(result)   # tüm indextekilere 10 eklemiş olduk

# farklarını da alabiliriz
result = numbers1 - numbers2
print(result)

# şöyle yapalım
result = numbers1 - 10
print(result)   # tüm elemanlardan 10 çıkarılır

# çarpma işlemi de olur
result = numbers1 * numbers2
print(result)

# bölme işlemi de olur
result = numbers1 / numbers2
print(result)


# herhangi bir dizinin sinüsünü alalım
result = np.sin(numbers1)
print(result)

# cosinus ünü alalım
result = np.cos(numbers1)
print(result)

# sqrt metoduna verirsek
result = np.sqrt(numbers1)  # her bir elemanını karekökünü alır
print(result)

# logaritmasını alalım
result = np.log(numbers1)
print(result)


# multinumbers yapıp ([] ile gruplara ayırıp) işlemlere öyle devam edelim
mnumbers1 = numbers1.reshape(2,3)
mnumbers2 = numbers2.reshape(2,3)   # 2 satır 3 de kolon(sütun) olarak ayırdık(grupladık)

print(mnumbers1)
print(mnumbers2)

# bu gelen matrisleri birleştirmek istersek eğer...
result = np.vstack((mnumbers1,mnumbers2))   # vstack() dikey olarak birleştirir matrisleri
print("sa")
print(result)

result = np.hstack((mnumbers1, mnumbers2))  # hstack() yatay olarak birleştirdi matrixi
print(result)

# elemanların belli bir koşula uyup uymadığını kontrol edelim

# elemanların her biri için 5 ten büyük mü..
result = numbers1 >= 5
print(result)  # bool türünde değer gönderir

# şimdi 50 den büyük mü onu yapalım
result = numbers1 >= 50
print(result)

# (sayı çift mi tek mi) numbers1 den gelen her bir değerin mod iki sinin sıfıra eşit olup olmadığını kontrol edelim
result = numbers1 %2 == 0
print(result)

# True olan sonuçlar ayrı bir liste içersinde bize geri dönsün istersek
print(numbers1[result])


[96 17 48 27 21 27]
[24 17 10 61 10 58]
[120  34  58  88  31  85]
[106  27  58  37  31  37]
[ 72   0  38 -34  11 -31]
[86  7 38 17 11 17]
[2304  289  480 1647  210 1566]
[4.         1.         4.8        0.44262295 2.1        0.46551724]
[ 0.98358775 -0.96139749 -0.76825466  0.95637593  0.83665564  0.95637593]
[-0.18043045 -0.27516334 -0.64014434 -0.29213881 -0.54772926 -0.29213881]
[9.79795897 4.12310563 6.92820323 5.19615242 4.58257569 5.19615242]
[4.56434819 2.83321334 3.87120101 3.29583687 3.04452244 3.29583687]
[[96 17 48]
 [27 21 27]]
[[24 17 10]
 [61 10 58]]
sa
[[96 17 48]
 [27 21 27]
 [24 17 10]
 [61 10 58]]
[[96 17 48 24 17 10]
 [27 21 27 61 10 58]]
[ True  True  True  True  True  True]
[ True False False False False False]
[ True False  True False False False]
[96 48]
