# Demo Numpy

        1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

In [1]:
import numpy as np

numbers = np.array([10,15,30,45,60])
print(numbers)

[10 15 30 45 60]


        2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

In [8]:
import numpy as np

numbers = np.arange(6,15)
print(numbers)

[ 6  7  8  9 10 11 12 13 14]


        3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

In [9]:
import numpy as np

numbers = np.arange(50,100,5)
print(numbers)

[50 55 60 65 70 75 80 85 90 95]


        4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

In [10]:
import numpy as np

numbers = np.zeros(10)
print(numbers)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


        5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

In [11]:
import numpy as np

numbers = np.ones(10)
print(numbers)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


        6- (0-100) arasında eşit aralıklı 5 sayı üretin.

In [30]:
import numpy as np

numbers = np.linspace(0,100,5)
print(numbers)

[  0.  25.  50.  75. 100.]


        7- (10-30) arasında rastgele 5 tane tamsayı üretin.

In [33]:
import numpy as np

numbers = np.random.randint(10,30,5)
print(numbers)

[26 19 26 20 27]


        8- [-1 ile 1 ] arasında 10 adet sayı üretin.

In [37]:
import numpy as np

numbers = np.random.randn(10)
print(numbers)

[ 0.48022981 -0.48266361  0.01696774  0.4254545   0.59171291 -0.43292186
 -0.62505908  0.9069334  -0.93331987 -0.17241058]


        9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

In [41]:
matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)

[[27 42 24 24 28]
 [35 12 25 40 48]
 [37 18 32 30 34]]


        10- üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız?    

In [42]:
matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)

###-----

satirToplam = matris.sum(axis=1)
kolonToplam = matris.sum(axis=0)

print(satirToplam)
print(kolonToplam)

[[20 43 16 11 10]
 [34 11 16 14 28]
 [33 47 37 16 21]]
[100 103 154]
[ 87 101  69  41  59]


        11- üretilen matrisin en büyük, en küçük ve ortalaması nedir?

In [3]:
matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)

###-----

result = matris.max()
print(result)

result = matris.min()
print(result)

# ortalama bulalım
result = matris.mean()
print(result)

[[31 32 24 34 48]
 [26 31 38 25 47]
 [15 27 41 35 47]]
48
15
33.4


        12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

In [4]:
import numpy as np

matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)

###---matris ürettik--

result = matris.argmax()
print(result)

result = matris.argmin()
print(result)

[[38 11 15 33 26]
 [41 29 37 15 36]
 [21 35 23 33 46]]
14
1


        13 - (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

In [ ]:
# bir dizi tanımlayalım
arr = np.arange(10,20)  # arr diye salladık
print(arr)
# ilk 3 elemanını seçelim
result = arr[0:3]
print(result)

        14 - Üretilen dizinin elemanlarını tersten yazdırınız.

In [6]:
arr = np.arange(10,20)  # arr diye salladık
print(arr)
#----yukarısı aynı

result = arr[::-1]   # iki nokta anlamı --> tüm elemanları seç
                    # -1 anlamı --> teker teker al. (- olunca tersten teker teker)
print(result)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


        15 - Üretilen matrisin ilk satırını seçiniz.

In [8]:
matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)

###-----önceden ürettiğimiz matris

result = matris[0]
print("sa")
print(result)

[[25 16 11 13 15]
 [16 13 15 15 42]
 [44 22 32 29 19]]
sa
[25 16 11 13 15]


        16 - Üretilen matrisin 2. satır 3. sütunundaki elemanı hangisidir?

In [9]:
matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)

###-----önceden ürettiğimiz matris

result = matris[1,2]
print("sa")
print(result)

[[23 15 28 44 27]
 [27 39 17 27 46]
 [29 10 10 21 27]]
sa
17


        17 - Üretilen matrisin tüm satırlarındaki ilk elemanı seçiniz.

In [12]:
matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)

###-----önceden ürettiğimiz matris

result = matris[::,0]
print("sa")
print(result)

[[44 35 23 19 45]
 [19 39 47 14 33]
 [39 14 20 30 10]]
sa
[44 19 39]


        18 - Üretilen matrisin her bir elemanının karesini alınız.

In [14]:
matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)

###-----önceden ürettiğimiz matris

result = matris ** 2
print("sa")
print(result)

[[28 19 40 48 46]
 [29 15 12 41 33]
 [43 46 28 41 13]]
sa
[[ 784  361 1600 2304 2116]
 [ 841  225  144 1681 1089]
 [1849 2116  784 1681  169]]


        19 - Üretilen matris elemanlarının hangisi pozitif çift sayıdır ?
                Aralığı (-50,+50) arasında yapınız.

In [37]:
matris = np.random.randint(-50,50,15).reshape(3,5)
print(matris)

###----matrisi değiştirip -50,50 yaptık busefer
result_cift = matris[matris %2 == 0] # bu şekilde yaparsak istediğimiz (true değerler) bilgileri geri döndürüyor sadece
result = result_cift[result_cift > 0]
print(result)


[[-25 -50 -20  13 -49]
 [ 16  46  41 -44 -38]
 [-31 -43  39 -19   2]]
[16 46  2]
