# Pandas Data Frame İle Veri Filtreleme

In [3]:
import pandas as pd
import numpy as np

# data isimli seri üretiyoruz  , reshape ile 15 satır 5 kolona bölüyoruz. matrix oldu
data = np.random.randint(10,100,75).reshape(15,5)
print(data)

[[93 78 86 18 60]
 [11 25 30 27 80]
 [24 44 30 56 24]
 [31 53 16 84 23]
 [90 36 58 83 80]
 [23 19 73 85 25]
 [75 49 97 93 49]
 [40 70 64 18 20]
 [36 67 73 21 17]
 [25 61 48 19 87]
 [34 47 84 76 90]
 [77 20 64 94 34]
 [22 75 27 13 42]
 [33 95 36 15 70]
 [87 22 11 10 49]]


* data yı DataFrame'e verelim

In [5]:
import pandas as pd

# dataFrame olarak tanımlayalım dataFrame'e verelim datayı
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])                      
result = df                         # kolonları belirttik index ismi vermedik otomatik
print(result)

    Column1  Column2  Column3  Column4  Column5
0        93       78       86       18       60
1        11       25       30       27       80
2        24       44       30       56       24
3        31       53       16       84       23
4        90       36       58       83       80
5        23       19       73       85       25
6        75       49       97       93       49
7        40       70       64       18       20
8        36       67       73       21       17
9        25       61       48       19       87
10       34       47       84       76       90
11       77       20       64       94       34
12       22       75       27       13       42
13       33       95       36       15       70
14       87       22       11       10       49


* diyelimki bizim elimizde bir csv dosyası ve içinde yüksek boyutta bilgi var

In [12]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# csv dosyasındaki bilgileri dataFrame'e aktarıcam ve kolon bilgilerini merak ediyorsam ne yapmalıyım.
result = df.columns
print(result)   # dataFrame içindeki kolonların bilgisini verdi.

# csv dosyasındaki baştan ilk 5 bilgiyi almak istiyoruz diyelim
result = df.head()
print(result)   # ilk 5 satırı verdi

# baştan ilk 10 kaydı nasıl alabiliriz mesela
result = df.head(10)
print(result)

# sondan ilk 5 bilgi nasıl alırım
result = df.tail()
print(result)

# sondan ilk 10 bilgiyi..
result = df.tail(10)
print(result)

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5'], dtype='object')
   Column1  Column2  Column3  Column4  Column5
0       93       78       86       18       60
1       11       25       30       27       80
2       24       44       30       56       24
3       31       53       16       84       23
4       90       36       58       83       80
   Column1  Column2  Column3  Column4  Column5
0       93       78       86       18       60
1       11       25       30       27       80
2       24       44       30       56       24
3       31       53       16       84       23
4       90       36       58       83       80
5       23       19       73       85       25
6       75       49       97       93       49
7       40       70       64       18       20
8       36       67       73       21       17
9       25       61       48       19       87
    Column1  Column2  Column3  Column4  Column5
10       34       47       84       76       90
11       77       20      

* devam edelim

In [30]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# sadece seçilen kolonun baştan ilk 5 kaydını alır
result = df["Column1"].head()
print(result)
print("            --")

# yukarıdakini şöyle de yaparsak aynı sonuca çıkar
result = df.Column1.head()
print(result)
print("            --")

# birden fazla kolon almak istersek.
result = df[["Column1", "Column2"]].head() # birden fazla kolon isteyince liste olarak göndermek gerekiyor.
print(result)           # kolon bir kolon iki nin ilk 5'i gelir.
print("            --")

# aynısının bu sefer sondan ilk 5 kayıtları alalım
result = df[["Column1", "Column2"]].tail() # birden fazla kolon isteyince liste olarak göndermek gerekiyor.
print(result)           # kolon bir kolon iki nin ilk 5'i gelir.

0    93
1    11
2    24
3    31
4    90
Name: Column1, dtype: int32
            --
0    93
1    11
2    24
3    31
4    90
Name: Column1, dtype: int32
            --
   Column1  Column2
0       93       78
1       11       25
2       24       44
3       31       53
4       90       36
            --
    Column1  Column2
10       34       47
11       77       20
12       22       75
13       33       95
14       87       22


* parçalayıp dataFrame'in istediğimiz bir parçasını da alabiliriz

In [38]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# dataFrame in 5 ile 15. indexleri arasındaki kayıtların kolon1 ve kolon2 sinin ilk 5'ini al
result = df[5:15][["Column1", "Column2"]].head()
print(result)
print("            --")


# yukarıdakinin son 5 kayıt olan halini alalım
result = df[5:15][["Column1", "Column2"]].tail()
print(result)

   Column1  Column2
5       23       19
6       75       49
7       40       70
8       36       67
9       25       61
            --
    Column1  Column2
10       34       47
11       77       20
12       22       75
13       33       95
14       87       22


### Filtreleme işlemleri

In [45]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# dataFrame deki 50 den büyük tüm bilgilere True & False verir.
result = df > 50
print(result)

    Column1  Column2  Column3  Column4  Column5
0      True     True     True    False     True
1     False    False    False    False     True
2     False    False    False     True    False
3     False     True    False     True    False
4      True    False     True     True     True
5     False    False     True     True    False
6      True    False     True     True    False
7     False     True     True    False    False
8     False     True     True    False    False
9     False     True    False    False     True
10    False    False     True     True     True
11     True    False     True     True    False
12    False     True    False    False    False
13    False     True    False    False     True
14     True    False    False    False    False


In [50]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# eğer true olan değerleri istersek..
result = df[df > 50]
print(result)   # 50 den büyük olmayanlar için NaN der

    Column1  Column2  Column3  Column4  Column5
0      93.0     78.0     86.0      NaN     60.0
1       NaN      NaN      NaN      NaN     80.0
2       NaN      NaN      NaN     56.0      NaN
3       NaN     53.0      NaN     84.0      NaN
4      90.0      NaN     58.0     83.0     80.0
5       NaN      NaN     73.0     85.0      NaN
6      75.0      NaN     97.0     93.0      NaN
7       NaN     70.0     64.0      NaN      NaN
8       NaN     67.0     73.0      NaN      NaN
9       NaN     61.0      NaN      NaN     87.0
10      NaN      NaN     84.0     76.0     90.0
11     77.0      NaN     64.0     94.0      NaN
12      NaN     75.0      NaN      NaN      NaN
13      NaN     95.0      NaN      NaN     70.0
14     87.0      NaN      NaN      NaN      NaN


* devam

In [52]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# çift olup olmadığına bakalım
result = df[df %2 == 0]
print(result)   # çift olmayanlara NaN dedi

    Column1  Column2  Column3  Column4  Column5
0       NaN     78.0     86.0     18.0     60.0
1       NaN      NaN     30.0      NaN     80.0
2      24.0     44.0     30.0     56.0     24.0
3       NaN      NaN     16.0     84.0      NaN
4      90.0     36.0     58.0      NaN     80.0
5       NaN      NaN      NaN      NaN      NaN
6       NaN      NaN      NaN      NaN      NaN
7      40.0     70.0     64.0     18.0     20.0
8      36.0      NaN      NaN      NaN      NaN
9       NaN      NaN     48.0      NaN      NaN
10     34.0      NaN     84.0     76.0     90.0
11      NaN     20.0     64.0     94.0     34.0
12     22.0      NaN      NaN      NaN     42.0
13      NaN      NaN     36.0      NaN     70.0
14      NaN     22.0      NaN     10.0      NaN


* devam

In [64]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# istediğimiz bir kolon üzerinden bu filtrelemeyi yapalım
# 1. kolonda 50 den büyük olanları göstersin
result = df["Column1"] > 50
print(result)
print("            --")


# column 1 in 50 den büyük olduğu satırlardaki kayıtları versin sadece
result = df[df["Column1"] > 50]
print(result)
print("            --")

0      True
1     False
2     False
3     False
4      True
5     False
6      True
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14     True
Name: Column1, dtype: bool
            --
    Column1  Column2  Column3  Column4  Column5
0        93       78       86       18       60
4        90       36       58       83       80
6        75       49       97       93       49
11       77       20       64       94       34
14       87       22       11       10       49
            --


* devam

        & (and yerine kullanılır)

In [74]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# yukarıdaki gelen kolonlardaki verilerden de istediğimiz kolonu seçelim
result = df[df["Column1"] > 50][["Column1","Column2"]]
print(result)
print("            --")


# koşulları artıralım
# kolon1 50 den 70 e kadar olan satırların tüm bilgileri geliyor dikkat!
result = df[(df["Column1"] > 50) & (df["Column1"] <= 70)]
print(result)

    Column1  Column2
2        62       33
4        61       40
5        63       76
9        70       80
11       68       48
            --
    Column1  Column2  Column3  Column4  Column5
2        62       33       42       41       92
4        61       40       42       27       94
5        63       76       96       61       49
9        70       80       78       57       90
11       68       48       38       47       16


* devam

        | (pipe işareti) : or yerine kullanılır
        
        query()

In [81]:
import pandas as pd
import numpy as np
data = np.random.randint(10,100,75).reshape(15,5)
df = pd.DataFrame(data, columns= ["Column1", "Column2", "Column3", "Column4", "Column5"])
#--- temel kod

# or operatörü (pipe işareti) |
# or ile koşul yapalım
result = df[(df["Column1"] > 50) | (df["Column1"] <= 70)]
print(result)   # sadece bir koşulu sağlaması yetiyor
print("            --")

# koşullarımızı query ye verebiliyoruz
# kolon1 50 den büyük eşit ve çift olsun
result = df.query("Column1 >= 50 & Column1 %2 == 0")
print(result)
print("            --")


# yukarıdakine bir de kolon filtrelemesi ekleyelim
result = df.query("Column1 >= 50 & Column1 %2 == 0")[["Column1","Column2"]]
print(result) # bu işlemleri kolon bir ve kolon2 de uygulasın diye ekledik

    Column1  Column2  Column3  Column4  Column5
0        91       25       47       63       10
1        53       61       46       41       20
2        93       78       72       66       51
3        27       53       19       23       52
4        20       18       45       63       22
5        93       48       57       63       29
6        28       37       11       79       59
7        54       89       34       97       86
8        64       16       25       99       90
9        44       74       15       20       65
10       62       88       91       73       21
11       67       38       47       84       86
12       57       15       71       24       68
13       95       52       24       95       12
14       15       44       67       99       14
            --
    Column1  Column2  Column3  Column4  Column5
7        54       89       34       97       86
8        64       16       25       99       90
10       62       88       91       73       21
            --
    Column